name: Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-142-57-178.ap-southeast-1.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/forum-api-starter-project

            # Pull latest code (rsync will overwrite it in next step, but this is optional safety)
            git reset --hard
            git clean -fd

            exit
          EOF

          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" . ubuntu@ec2-18-142-57-178.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/forum-api-starter-project/

          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-142-57-178.ap-southeast-1.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/forum-api-starter-project

            # Install new dependencies if package.json changed
            npm install

            # Run DB migrations (optional if already migrated)
            npm run migrate up

            # Restart using PM2
            pm2 restart app || pm2 start src/app.js --name app
          EOF
