name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test-success:
    name: Run Passing Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: forumapi_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 24681012
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST_TEST: localhost
      PGUSER_TEST: postgres
      PGPASSWORD_TEST: 24681012
      PGDATABASE_TEST: forumapi_test
      PGPORT_TEST: 5432
      NODE_ENV: test
      ACCESS_TOKEN_KEY: IniAdalahAccessTokenKeyYangSangatPanjangDanAman1234567890
      REFRESH_TOKEN_KEY: IniAdalahRefreshTokenKeyYangSangatPanjangDanAman1234567890
      ACCCESS_TOKEN_AGE: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run test DB migration
        run: npm run migrate:test up

      - name: Run passing tests
        run: npm run test
